//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultas()
        {
            this.Prescripciones = new HashSet<Prescripciones>();
        }
    
        public int Consultas_Id { get; set; }
        public int Paciente_Id { get; set; }
        public Nullable<int> EPS_Id { get; set; }
        public string Cargo { get; set; }
        public string Empresa { get; set; }
        public string Fecha_Consulta { get; set; }
        public string Tipo_de_Examen { get; set; }
        public string Estado_Civil { get; set; }
        public string Calificacion_Medica { get; set; }
        public string Observaciones { get; set; }
    
        public virtual EPS EPS { get; set; }
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescripciones> Prescripciones { get; set; }
    }
}
